type = "mono"
image_folder = "TODO"

#[pattern]
#type = "checkerboard"
#shifted = "true"
#TODO


[[preprocessing.operations]]
name = "grayscale"
enabled = true

[[preprocessing.operations]]
name = "gamma"
gamma = 0.4

[[preprocessing.operations]]
name = "clahe"
tile_size = [8, 8]
clip_limit = 2.0

[[preprocessing.operations]]
name = "gamma"
gamma = 1.2
